# Generated by Django 4.1.7 on 2023-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsgame',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sportsgame',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
