# Generated by Django 4.1.7 on 2023-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_remove_sportsgame_desc_sportsgame_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsgame',
            name='image',
            field=models.ImageField(null=True, upload_to='img/other_img'),
        ),
    ]
